### ISSUE TITLE
Results impact of planarMotion

### ISSUE THREAD

**Issue by MaXZon3** [jhu-lcsr/handeye_calib_camodocal#18]
Hi,

Using your handeye calibration, I'm wondering what is the impact of this boolean `planarMotion` parameter.

According to what I read in the code, it's always fixed to `false`.

Is it possible to explain what it implies on the final results please? :smile: 

https://github.com/jhu-lcsr/handeye_calib_camodocal/blob/2073c770ee8b45428862bacd6d80a23761aa1d83/src/camodocal/calib/HandEyeCalibration.cc#L114

**Comment by ahundt** [comment]
that's an artifact of the original source for some of the calibration code, which worked on a car, and since a car can't go up in the air very easily I believe this was a special case to help with the situation. I never dealt with that part specifically because I didn't do any planar motions, so I don't have an exact answer at the moment, sorry.
